INSERT OR IGNORE INTO authors (id, name, bio, role, email) VALUES
('author-1', 'Maria Santos', 'Senior political correspondent', 'Senior Correspondent', 'maria@veritasnexus.ph'),
('author-2', 'Renato Cruz', 'Economy and business reporter', 'Business Reporter', 'renato@veritasnexus.ph'),
('author-3', 'Lourdes Reyes', 'Agriculture and rural affairs reporter', 'Agriculture Correspondent', 'lourdes@veritasnexus.ph'),
('author-4', 'Jose Delos Santos', 'Environment and climate reporter', 'Environment Reporter', 'jose@veritasnexus.ph');

INSERT OR IGNORE INTO policy_projects (id, name, slug, agency, budget, status, description, start_date, target_date, updates, section_tag) VALUES
('policy-1', 'Metro Manila Subway', 'metro-manila-subway', 'DOTr', '488.5B', 'Ongoing', 'A 33-kilometer underground railway system connecting Quezon City to Paranaque.', '2019-01-01', '2028-12-31', '[]', 'Infrastructure'),
('policy-2', 'Rice Self-Sufficiency Program', 'rice-self-sufficiency', 'DA', '45B', 'Delayed', 'National program to achieve rice self-sufficiency through increased production and irrigation.', '2022-01-01', '2027-12-31', '[]', 'Agriculture'),
('policy-3', 'AFP Modernization Phase 3', 'afp-modernization-phase-3', 'DND', '300B', 'Ongoing', 'Third phase of the Armed Forces modernization program covering 2023-2028.', '2023-01-01', '2028-12-31', '[]', 'Defense'),
('policy-4', 'MRT-7 Extension', 'mrt-7-extension', 'DOTr', '62.7B', 'Ongoing', 'Extension of MRT-7 from San Jose Del Monte to Bulacan.', '2020-06-01', '2027-06-01', '[]', 'Infrastructure'),
('policy-5', 'National Irrigation Development', 'national-irrigation-dev', 'NIA', '45B', 'Delayed', 'Expansion of irrigation systems across major agricultural regions.', '2021-01-01', '2026-12-31', '[]', 'Agriculture');

INSERT OR IGNORE INTO timeline_topics (id, name, slug, description, entries) VALUES
('timeline-1', 'West Philippine Sea Dispute', 'west-philippine-sea', 'Ongoing territorial dispute between the Philippines and China in the South China Sea.', '[{"id":"t1-1","date":"2016-07-12","year":2016,"heading":"Arbitration Ruling","summary":"The Hague tribunal ruled in favor of the Philippines."},{"id":"t1-2","date":"2023-08-05","year":2023,"heading":"Water Cannon Incident","summary":"Chinese coast guard fired water cannons at Philippine resupply vessels."},{"id":"t1-3","date":"2024-02-11","year":2024,"heading":"PH-US Cooperation Expanded","summary":"Philippines and US formalized expanded EDCA implementation.","isCurrent":true}]'),
('timeline-2', 'AFP Modernization Program', 'afp-modernization', 'Long-running program to upgrade Philippine military capabilities.', '[{"id":"t2-1","date":"1995-02-25","year":1995,"heading":"RA 7898 Enacted","summary":"The AFP Modernization Act was signed into law."},{"id":"t2-2","date":"2013-01-01","year":2013,"heading":"Phase 1 Begins","summary":"First phase with 75B budget launched."},{"id":"t2-3","date":"2023-01-01","year":2023,"heading":"Phase 3 Current","summary":"Third phase with 300B allocation underway.","isCurrent":true}]'),
('timeline-3', 'Rice Import Policy', 'rice-import-policy', 'Evolution of Philippine rice importation policies.', '[{"id":"t3-1","date":"2019-02-14","year":2019,"heading":"Rice Tariffication Law","summary":"RA 11203 liberalized rice trade replacing quotas with tariffs."},{"id":"t3-2","date":"2023-08-15","year":2023,"heading":"Price Cap Implemented","summary":"Government imposed price cap on rice amid surging prices."},{"id":"t3-3","date":"2024-03-01","year":2024,"heading":"Import Volumes Rise","summary":"Rice imports reached record levels as domestic production fell short.","isCurrent":true}]');

INSERT OR IGNORE INTO articles (id, title, slug, excerpt, content, article_type, published_at, author_id, primary_section, tags, sources, what_it_means, read_time) VALUES
('article-1', 'Philippine Coast Guard Repels Chinese Water Cannon Attack in Second Thomas Shoal', 'ph-south-china-sea-patrol', 'Philippine vessels conducting a resupply mission to BRP Sierra Madre faced sustained water cannon fire from Chinese coast guard ships.', 'The Philippine Coast Guard successfully completed a resupply mission to BRP Sierra Madre despite sustained water cannon fire from Chinese vessels. The incident marks the third such attack this year.', 'NewsAnalysis', '2026-03-14', 'author-1', 'National', '["West Philippine Sea","China","Coast Guard","Sovereignty"]', '[{"type":"Official Document","label":"PCG Official Statement","url":"https://pcg.gov.ph"}]', '[{"stakeholder":"For diplomacy","effect":"Increased pressure on China through international channels"},{"stakeholder":"For military","effect":"Justification for expanded US-PH joint patrols"}]', 6),
('article-2', 'Marcos Administration Accelerates Infrastructure Program Amid Funding Concerns', 'marcos-infrastructure-push', 'The government has fast-tracked approvals for 47 major infrastructure projects this quarter.', 'The Marcos administration has accelerated its Build Better More infrastructure program, fast-tracking 47 major projects worth a combined 1.2 trillion pesos.', 'IntelligenceBrief', '2026-03-13', 'author-2', 'Economy', '["Infrastructure","Budget","Debt"]', '[{"type":"Government Data","label":"DBCC Report Q1 2026"}]', '[{"stakeholder":"For taxpayers","effect":"Higher debt servicing costs in coming years"},{"stakeholder":"For construction sector","effect":"Significant project pipeline through 2028"}]', 8),
('article-3', 'NFA Price Cap Fails to Curb Rice Inflation in Metro Manila', 'rice-prices-nfa-intervention', 'Despite a price ceiling on NFA rice, private traders continue selling premium varieties above 55 pesos per kilo.', 'The National Food Authority price cap on rice has failed to contain retail prices in Metro Manila, with private traders selling premium varieties at 55-65 pesos per kilogram.', 'NewsAnalysis', '2026-03-12', 'author-3', 'Agriculture', '["Rice","NFA","Food Prices","Inflation"]', '[{"type":"Data","label":"PSA Consumer Price Index March 2026"}]', '[{"stakeholder":"For farmers","effect":"Lower farmgate prices due to import competition"},{"stakeholder":"For consumers","effect":"Short-term price relief but long-term supply uncertainty"}]', 5);
